services:
  hallo_verden_notification_api_sms_notifier.bearer_token_provider:
    class: Fagforbundet\NotificationApiSmsNotifierBundle\Token\BearerTokenProvider
    arguments:
      - '@HalloVerden\Oidc\ClientBundle\Interfaces\OpenIdProviderRegistryServiceInterface'
      - '@cache.app'

  hallo_verden_notification_api_sms_notifier.transport_factory:
    class: Fagforbundet\NotificationApiSmsNotifierBundle\Transport\NotificationApiTransportFactory
    arguments:
      - '@hallo_verden_notification_api_sms_notifier.bearer_token_provider'
      - '@event_dispatcher'
      - '@http_client'
    tags:
      - { name: texter.transport_factory }
